CREATE TABLE IF NOT EXISTS entries (
  id SERIAL PRIMARY KEY,
  content TEXT NOT NULL,
  created_at DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATE DEFAULT NULL,
  user_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
)
