definitions:
  controller.GetAllEntriesResult:
    properties:
      data:
        type: string
    type: object
  controller.LoginResult:
    properties:
      jwt:
        type: string
    type: object
  model.AuthenticationInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.Entry:
    properties:
      content:
        type: string
      userID:
        type: integer
    type: object
  model.User:
    properties:
      entries:
        items:
          $ref: '#/definitions/model.Entry'
        type: array
      id:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
  description: Simple example of BE
  title: Simple BE
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.AuthenticationInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.LoginResult'
      summary: Login a user
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.AuthenticationInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
      summary: Register a new user
  /entry:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetAllEntriesResult'
      summary: Get all entries
    post:
      consumes:
      - application/json
      parameters:
      - description: Entry details
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.Entry'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Entry'
      summary: Add a new entry
swagger: "2.0"
